---
title: "Data Manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

## Load the FAS Litters data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
litters_df
```

## 'select' 

select lets us choose some columns and not others 

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns

```{r}
select(litters_df, GROUP = group, LITTer_NUmbeR = litter_number)
```

```{r}
rename(litters_df, GROUP = group, LITTer_NUmbeR = litter_number)
```

Select helpers - help to quickly select

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```
these do the same thing ^
```{r}
relocate(litters_df, litter_number)
```

## 'filter' 

filter operates on rows while select operates on columns - you have to give filter a True vs False condition - use logical operators 

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

Logical ooperators for 'filter' 

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
```
! flips the logical operation

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Mod8", "Con7"))
```
